/*
 * @Author: Delevin.TnT
 * @LastEditors: Delevin.TnT
 * @Date: 2022-02-14 11:00:08
 * @LastEditTime: 2022-02-22 11:11:59
 */
export enum FILETYPE {
  'file-0' = '-',
  'file-1' = 'exe',
  'file-2' = 'dll',
  'file-3' = 'elf',
  'file-4' = 'doc',
  'file-5' = 'docx',
  'file-6' = 'ppt',
  'file-7' = 'pptx',
  'file-8' = 'xls',
  'file-9' = 'xlsx',
  'file-10' = 'pdf',
  'file-11' = 'html',
  'file-12' = 'powershell',
  'file-13' = 'vbs',
  'file-14' = 'js',
  'file-15' = 'jsp',
  'file-16' = 'zip',
  'file-17' = 'rar',
  'file-18' = '7z',
  'file-19' = 'tar',
  'file-20' = 'gz',
  'file-21' = 'rtf',
  'file-22' = 'asp',
  'file-23' = 'xmind',
  
  'file-24' = 'png',
  'file-25' = 'jpg',
  'file-26' = 'gif',
  'file-27' = 'bz',
  'file-28' = 'bmp',
  'file-29' = 'dwg',
  'file-30' = 'psd',
  'file-31' = 'eml',
  'file-32' = 'vsd',
  'file-33' = 'mdb',
  'file-34' = 'ps',
  'file-35' = 'rmvb',
  'file-36' = 'flv',
  'file-37' = 'mp4',
  'file-38' = 'mp3',
  'file-39' = 'mpg',
  'file-40' = 'wmv',
  'file-41' = 'wav',
  'file-42' = 'avi',
  'file-43' = 'mid',
  'file-44' = 'ram',
  'file-45' = 'css',
  'file-46' = 'ini',
  'file-47' = 'xml',
  'file-48' = 'sql',
  'file-49' = 'java',
  'file-50' = 'bat',
  'file-51' = 'mf',
  'file-52' = 'torrent',
  'file-53' = 'mov',
  'file-54' = 'wpd',
  'file-55' = 'dbx',
  'file-56' = 'pst',
  'file-57' = 'qdf',
  'file-58' = 'txt',
}
